# Generated by Django 4.2 on 2026-04-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['group__display_order', 'display_order', 'id']},
        ),
    ]
