# Generated by Django 4.2 on 2026-04-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_route_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eta_offset_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.route')),
            ],
            options={
                'ordering': ['route__display_order', 'sequence', 'id'],
                'unique_together': {('route', 'sequence')},
            },
        ),
    ]
