# Generated by Django 4.2 on 2026-04-22 01:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0002_alter_route_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('speed_kph', models.PositiveIntegerField(default=0)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('occupancy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('traffic_level', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='moderate', max_length=20)),
                ('packet_loss_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_online', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to='routing.tripbusassignment')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_liters', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actual_liters', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_readings', to='routing.tripbusassignment')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
    ]
