# Generated by Django 4.2 on 2026-04-22 10:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0003_routestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=80, unique=True)),
                ('api_key', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('firmware_version', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='routing.bus')),
            ],
            options={
                'ordering': ['bus__code', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kph', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ignition_on', models.BooleanField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='routing.tripbusassignment')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='routing.bus')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='tracking.busdevice')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='routing.trip')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['bus', '-recorded_at'], name='tracking_bu_bus_id_8dddb2_idx'),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['assignment', '-recorded_at'], name='tracking_bu_assignm_e5787d_idx'),
        ),
    ]
